vesopenapimanager:
  validation:
    schemaMapPath: ${SCHEMA_MAP_PATH:./src/main/resources/schema-map.json}
    eventDomainPath: /event/structure/commonEventHeader/structure/domain/value
    eventSchemaReferencePath: /event/structure/stndDefinedFields/structure/schemaReference/value
  distribution:
    asdcAddress: ${ASDC_ADDRESS:sdc-be.onap:30204}
    msgBusAddress: message-router.onap
    user: dcae
    password: Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U
    pollingInterval: 20
    pollingTimeout: 20
    consumerGroup: ves-openapi-manager
    environmentName: AUTO
    consumerID: ves-openapi-manager
    activateServerTLSAuth: false
    isFilterInEmptyResources: false
    isUseHttpsWithDmaap: false


